name: Build

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm run build
