name: CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  format:
    uses: ./.github/workflows/check-formatting.yml
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml

  npm:
    if: github.ref == 'refs/heads/main'
    needs: [format, lint, test]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
